version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    volumes:
      - ./:/app  
    ports:
      - "8000:8000"  
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  